name: Actualisation horaire RTE

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  mise-a-jour:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: 📥 Récupération du code
        uses: actions/checkout@v4

      - name: 🐍 Configuration de Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 📦 Installation des dépendances
        run: pip install -r requirements.txt

      - name: 🚀 Exécution du script RTE
        env:
          RTE_CLIENT_ID: ${{ secrets.RTE_CLIENT_ID }}
          RTE_CLIENT_SECRET: ${{ secrets.RTE_CLIENT_SECRET }}
        run: python script_rte.py

 - name: 💾 Sauvegarde du JSON
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data_nucleaire_france.json
          # S'il y a une différence, on commit, on télécharge vos dernières modifs, puis on pousse
          git diff --quiet && git diff --staged --quiet || (git commit -m "⚡ MAJ auto de la production" && git pull --rebase origin main && git push)